### PR TITLE
labels qa

### PR DESCRIPTION
**Pull request by lzonneke**
added some labels used in the quality process

### CODE REVIEW

**Comment by despiegk** [comment]
lets discuss the potential new repo?
maybe its the best approach, but yet another repo seems like a lot.
we already defined the label 'test' for test tasks
idea is to use a markdown doc to generate test tasks.

lets discuss

**Comment by wimpers** [comment]
All code repositories will typically have tests for their own part of the code and the result should be labeled with (Travis) badge 'build passing' like https://docs.travis-ci.com/user/status-images/.

It might make sense to use have a repo for continuous integration testing. Automated testing could generate automatically an issue in case of an error. This issue needs to be analysed to see if it is a bug or a fault in the tests.

**Comment by lzonneke** [comment]
For the moment we have 3 repo's used in quality but you are right. We could move all testing into one single repo called org_qa into the gig-projects company ...

below are the repo's currently in use:
- our repo for automated test
  https://github.com/0-complexity/openvcloud_quality_testsuite
  --> used for automated test (currently on Jenkins), we could use travis but that would have again some impact and a new learning curve for testers... Also the cost for a private repo is 129$ per month
- our performance repo
  https://github.com/0-complexity/openvcloud_quality_performancetest
  --> used for testing the boundaries of our system
- Portal test repo
  https://github.com/0-complexity/portal_quality_testsuite

Test descriptions are done in issues. Every day I have a scrum meeting discussing the progress of the test scripts/issues with the quality team using Waffle. 

When we have found a bug we report this into the following repo...
https://github.com/0-complexity/openvcloud

In this repo milestones and timing is set. Then every week Quality (Ramez & me), Operations (David), and engineering (Jo), Jan, Yves and optional Jurgen are discussing all the bugs and planning in the BAM meeting (Bug Assesment Meeting). At least I invite all people to follow up on progress.

So for the future I would like to suggest to migrate the "https://github.com/0-complexity/openvcloud" repo to the company gig-projects with the following name proj_openvcloud.

Migrate those 3 quality repo's into 1 repo called org_qa...

When all is migrated we can still decide to use travis or Jenkins...

Let me know your toughts...

**Comment by despiegk** [comment]
will be hard to automatically merge in, I made to many changes in mean time
can someone please do this manually for what is relevant
please make sure read the whole doc first, quite some changes

**Comment by despiegk** [comment]
+lesley
+wimpers

**Comment by despiegk** [comment]
@lzonneke 
@wimpers 
@yveskerwyn

**Comment by yveskerwyn** [comment]
Will close this pull request without merging since proposed changes were already in

**Pull request closed without merging**
